### ISSUE TITLE
Cache restoration  Performance issues 

### ISSUE THREAD

**Issue by rigoucr** [fourkitchens/project_ci#33]
Currently the process is taking so long (+10 min) , and I think this had to do with the following image:
<img width="1603" alt="Screenshot 2023-08-08 at 1 36 44 PM" src="https://github.com/fourkitchens/project_ci/assets/2217827/fe356571-4b75-4095-9c6e-27c3f7612769">

As you can see we are having permissions issues to write (Create) some folders and also:

<img width="993" alt="Screenshot 2023-08-08 at 1 42 20 PM" src="https://github.com/fourkitchens/project_ci/assets/2217827/76b49eae-5fbf-4ad4-907a-249b1d32077e">

and it stills downloading all the composer packages , which shouldn't be happening because all those packages should be restored with cache restoring step.

**Comment by generalredneck** [comment]
@rigoucr check the latest version. Can  you validate that this still happens?

**Comment by generalredneck** [comment]
@rigoucr I'm going to mark this as fixed given that we removed composer install on the deploy to Pantheon jobs. This means that that cache isn't restored and therefore not producing any errors between the Circle convenience docker image and the Pantheon Docker Image.  You will need to upgrade your config.yml on the project you are experiencing this on.
